name = "link"
type = "javascript"
account_id = "8e16e06885cf66c58ff2224b65824658"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "LINKS", id = "163ed0c6bc82422baaa25ebcdc717178", preview_id = "163ed0c6bc82422baaa25ebcdc717178" }
]
